/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#fecdb4',
        'on-primary-container': '#d0eba1',
        'surface-dim': '#dcdad2',
        'on-secondary-fixed': '#2e1506',
        'on-tertiary-fixed': '#281719',
        'inverse-surface': '#30312c',
        'on-surface': '#1b1c17',
        'outline-variant': '#c5c8b8',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#fbdbde',
        outline: '#75796b',
        background: '#fbf9f1',
        'primary-fixed-dim': '#b6d088',
        'on-secondary-container': '#795541',
        secondary: '#7a5642',
        'on-error': '#ffffff',
        'inverse-primary': '#b6d088',
        'surface-container-high': '#eae8e0',
        primary: '#3e5219',
        'secondary-fixed-dim': '#ecbda4',
        error: '#ba1a1a',
        'on-primary-fixed': '#131f00',
        'surface-container-highest': '#e4e3db',
        'on-secondary-fixed-variant': '#603f2d',
        'tertiary-container': '#765e61',
        'surface-container': '#f0eee6',
        'surface-tint': '#50652a',
        'primary-fixed': '#d2eca2',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        tertiary: '#5d4649',
        'tertiary-fixed-dim': '#debfc2',
        surface: '#fbf9f1',
        'on-surface-variant': '#45483c',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#394d14',
        'secondary-fixed': '#ffdbca',
        'on-background': '#1b1c17',
        'primary-container': '#556b2f',
        'surface-variant': '#e4e3db',
        'error-container': '#ffdad6',
        'surface-bright': '#fbf9f1',
        'on-tertiary-container': '#fadadd',
        'inverse-on-surface': '#f3f1e9',
        'surface-container-low': '#f5f4ec',
        'on-tertiary-fixed-variant': '#574144',
      },
      fontFamily: {
        garamond: ['"EB Garamond"', 'serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'display-mobile': ['36px', { lineHeight: '44px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        gutter: '24px',
      },
      maxWidth: {
        'site': '1200px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}


