import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext(null)

const t = {
  ar: {
    brand: 'سايا',
    nav: { home: 'الرئيسية', shop: 'المتجر', about: 'عن سايا', contact: 'اتصل بنا' },
    hero: {
      badge: 'طبيعي ١٠٠٪',
      title: 'خليكي أجمل\nمع سايا',
      sub: 'اكتشفي سر الطبيعة في روتينك اليومي. منتجاتنا مستخلصة من أجود المكونات العضوية لتعتني بجمالك الشامل — من بشرتك وشعرك إلى كل تفصيلة فيكِ.',
      cta: 'تسوقي الآن',
      ctaSecondary: 'منتجاتنا الجديدة',
    },
    categories: {
      title: 'اكتشفي مجموعاتنا',
      skincare: { name: 'العناية بالبشرة', sub: 'أمصال، مرطبات، ومنظفات طبيعية' },
      perfumes: { name: 'العطور', sub: 'نفحات من الطبيعة تدوم طويلاً' },
      haircare: { name: 'منتجات الشعر', sub: 'زيوت وماسكات لتقوية الشعر من الجذور' },
      explore: 'استكشفي المجموعة',
    },
    bestsellers: {
      title: 'الأكثر مبيعاً',
      sub: 'اختيارات عملائنا المفضلة لهذا الموسم',
      add: 'أضف للسلة',
    },
    about: {
      label: 'فلسفتنا',
      quote: '"نؤمن أن الجمال الحقيقي يكمن في بساطة الطبيعة ونقاء الأرض."',
      body: 'في سايا، نسعى جاهدين لتقديم منتجات عناية بالبشرة لا تعالج فقط المشاكل الظاهرة، بل تغذي الروح وتدعم توازن الطبيعة. نحن نستخدم مكونات يتم حصادها بمسؤولية، وخالية تماماً من المواد الكيميائية القاسية.',
      checks: ['مكونات عضوية موثقة', 'صديق للبيئة (عبوات قابلة للتدوير)', 'لم يتم اختباره على الحيوانات'],
      readMore: 'اقرئي قصتنا كاملة',
      years: '١٠+ سنوات',
      yearsLabel: 'من الأبحاث في الطبيعة',
      heroTitle: 'جوهر الطبيعة في كل قطرة',
      heroSub: 'في سايا، نؤمن أن الجمال الحقيقي يكمن في البساطة والنقاء المستمد من قلب الأرض.',
      storyLabel: 'قصتنا',
      storyTitle: 'رحلة بدأت من شغف بالطبيعة',
      story1: 'تأسست سايا من رؤية بسيطة: ابتكار مستحضرات عناية بالبشرة تحترم توازن الطبيعة واحتياجات الإنسان المعاصر. بدأنا في معمل صغير يحيطه الهدوء، حيث كنا نمزج الزيوت النباتية والنقيع العشبي بكل حب وتفاني.',
      story2: 'اليوم، نفخر بأننا نصدر منتجاتنا لمن يقدرون الجودة والنقاء، مع الحفاظ على التزامنا الأول باستخدام أجود المكونات العضوية التي تغذي البشرة والروح.',
      tagline: 'سايا، حيث تلتقي الأرض بالجمال.',
      valuesTitle: 'رسالتنا وقيمنا',
      values: [
        { icon: 'eco', title: 'نقاء عضوي', body: 'نستخدم مكونات طبيعية 100%، مختارة بعناية من مزارع مستدامة تدعم البيئة والمجتمعات المحلية.' },
        { icon: 'spa', title: 'عناية للجميع', body: 'صُممت منتجاتنا لتلائم كافة أنواع البشرة، مع التركيز على المكونات اللطيفة والفعالة في آن واحد.' },
        { icon: 'science', title: 'أسس علمية', body: 'نجمع بين الحكمة القديمة في استخدام الأعشاب وأحدث ما توصل إليه العلم في مجال العناية بالبشرة.' },
      ],
      ingredientsLabel: 'مكوناتنا',
      ingredientsTitle: 'نظافة تفوق مجرد الكلمات',
      ingredientsBody: 'كل مكون يدخل في تركيباتنا يتم اختياره بناءً على قوته العلاجية وسلامته. نحن نرفض استخدام المواد الكيميائية القاسية، البارابين، أو العطور الاصطناعية.',
      ingredients: ['زيوت نباتية معصورة على البارد', 'نقيع أعشاب برية عضوية', 'زبدات طبيعية غير مكررة'],
      shopCta: 'اكتشف المتجر',
      founderQuote: '"الجمال لا يجب أن يكون معقداً. في سايا، نجعل الطبيعة تعتني ببشرتك لتعبري عن ذاتك بكل ثقة."',
      founderName: 'Sara Al-Fayez',
      founderRole: 'المؤسسة والمديرة الإبداعية',
    },
    reviews: { title: 'قالوا عن سايا', sub: 'تجارب حقيقية من نساء وجدن سر النضارة' },
    newsletter: {
      title: 'انضمي لعائلة سايا',
      body: 'اشتركي في نشرتنا البريدية للحصول على نصائح جمالية حصرية وخصم ١٥٪ على طلبك الأول.',
      placeholder: 'بريدك الإلكتروني',
      cta: 'اشترك الآن',
    },
    shop: {
      title: 'متجرنا الطبيعي',
      sub: 'اكتشفي سر الجمال العضوي المستخلص من قلب الطبيعة، للعناية الفائقة التي تليق بكِ.',
      filters: 'الأقسام',
      priceRange: 'نطاق السعر',
      sortBy: 'ترتيب حسب',
      sortOptions: ['الأحدث', 'السعر: من الأقل للأعلى', 'السعر: من الأعلى للأقل', 'الأكثر مبيعاً'],
      addToCart: 'إضافة للسلة',
      categories: ['الكل', 'العناية بالبشرة', 'العطور', 'العناية بالشعر', 'العروض'],
    },
    product: {
      rating: 'تقييم',
      qty: 'الكمية:',
      addCart: 'إضافة إلى السلة',
      buyNow: 'اشتري الآن',
      tabs: ['وصف المنتج', 'طريقة الاستخدام', 'المكونات الكاملة', 'الشحن والتبديل'],
      related: 'منتجات قد تعجبك',
      natural: 'مكونات طبيعية',
      tested: 'تم اختباره طبياً',
    },
    checkout: {
      title: 'إتمام الطلب',
      sub: 'يرجى ملء البيانات التالية لتأكيد طلبك',
      shipping: 'بيانات الشحن',
      fullName: 'الاسم بالكامل',
      phone: 'رقم الهاتف',
      email: 'البريد الإلكتروني (اختياري)',
      city: 'المحافظة',
      address: 'العنوان بالتفصيل',
      payment: 'طريقة الدفع',
      cod: 'الدفع عند الاستلام',
      codSub: 'ادفع نقداً لمندوب التوصيل عند استلام الطلب',
      wallet: 'تحويل محفظة / بنكي',
      walletSub: 'فودافون كاش، إنستا باي، أو تحويل بنكي',
      receipt: 'في حال اختيار التحويل، يرجى إرفاق صورة إيصال التحويل هنا:',
      upload: 'تحميل صورة الإيصال',
      summary: 'ملخص الطلب',
      discount: 'كود الخصم',
      apply: 'تطبيق',
      subtotal: 'المجموع الفرعي',
      shippingCost: 'الشحن',
      total: 'الإجمالي',
      confirm: 'تأكيد الطلب',
      terms: 'بضغطك على تأكيد الطلب، فأنت توافق على الشروط والأحكام',
    },
    contact: {
      title: 'يسعدنا تواصلكِ معنا',
      sub: 'في سايا، نؤمن بأن كل بشرة فريدة من نوعها. فريقنا المتخصص متواجد دائمًا للإجابة على استفساراتكِ ومساعدتكِ في اختيار الروتين الأمثل لجمالك الطبيعي.',
      formTitle: 'أرسلي لنا رسالة',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      subject: 'الموضوع',
      subjectOptions: ['استفسار عام', 'استشارة للعناية بالبشرة', 'مشكلة في الطلب', 'اقتراحات'],
      message: 'رسالتك',
      send: 'إرسال الرسالة',
      whatsapp: 'واتساب',
      emailLabel: 'البريد الإلكتروني',
      social: 'تابعينا على منصات التواصل',
      location: 'مقرنا الرئيسي',
      address: 'حي الروضة، طريق الملك عبدالله، الرياض، المملكة العربية السعودية',
      directions: 'الحصول على الاتجاهات',
      newsletterTitle: 'انضمي إلى عالم سايا',
      newsletterSub: 'اشتركي في نشرتنا البريدية لتصلكِ آخر أخبار منتجاتنا الطبيعية وعروضنا الحصرية.',
      newsletterCta: 'اشتركي الآن',
    },
    tracking: {
      title: 'تتبع طلبك',
      sub: 'أدخلي رقم الطلب الخاص بكِ لمتابعة رحلة منتجات سايا الطبيعية حتى تصل إلى عتبة دارك.',
      label: 'رقم الطلب',
      placeholder: 'مثال: SY-12345',
      cta: 'تتبع الحالة',
      exampleTitle: 'تفاصيل الشحن (مثال)',
      steps: ['تم استلام الطلب', 'قيد التجهيز', 'خرج للتوصيل', 'تم التسليم'],
      stepIcons: ['receipt_long', 'inventory_2', 'local_shipping', 'home_pin'],
      helpText: 'تواجهين مشكلة في تتبع طلبك؟',
      helpCta: 'تحدثي مع فريق العناية بالعملاء',
    },
    footer: {
      tagline: 'جمالك من الطبيعة، بلمسة عصرية. نحن نؤمن بالنقاء والفاعلية في كل قطرة.',
      shop: 'تسوقي حسب النوع',
      company: 'معلومات عن سايا',
      contactTitle: 'تواصل معنا',
      copyright: '© ٢٠٢٤ سايا. جميع الحقوق محفوظة.',
      privacy: 'سياسة الخصوصية',
      terms: 'الشروط والأحكام',
      address: 'القاهرة، مصر',
      phone: '+201102903151',
      emailAddr: 'hello@saya-skincare.com',
      links: {
        skincare: 'العناية بالبشرة',
        perfumes: 'العطور',
        hair: 'الشعر',
        about: 'عن سايا',
        shipping: 'الشحن',
        tracking: 'التتبع',
        contact: 'اتصل بنا',
      },
    },
  },
  en: {
    brand: 'SAYA',
    nav: { home: 'Home', shop: 'Shop', about: 'About', contact: 'Contact' },
    hero: {
      badge: '100% Natural',
      title: 'Be More Beautiful\nWith Saya',
      sub: 'Discover the secret of nature in your daily routine. Our products are extracted from the finest organic ingredients to restore your skin\'s vitality and radiance.',
      cta: 'Shop Now',
      ctaSecondary: 'New Arrivals',
    },
    categories: {
      title: 'Explore Our Collections',
      skincare: { name: 'Skincare', sub: 'Serums, moisturizers & natural cleansers' },
      perfumes: { name: 'Perfumes', sub: 'Nature\'s whispers that last all day' },
      haircare: { name: 'Haircare', sub: 'Oils & masks to strengthen hair from roots' },
      explore: 'Explore Collection',
    },
    bestsellers: {
      title: 'Best Sellers',
      sub: 'Our customers\' favourite picks this season',
      add: 'Add to Cart',
    },
    about: {
      label: 'Our Philosophy',
      quote: '"We believe true beauty lies in the simplicity and purity of nature."',
      body: 'At Saya, we strive to offer skincare products that not only treat visible problems but nourish the soul and support nature\'s balance. We use responsibly harvested ingredients, completely free from harsh chemicals and artificial preservatives.',
      checks: ['Certified organic ingredients', 'Eco-friendly (recyclable packaging)', 'Never tested on animals'],
      readMore: 'Read Our Full Story',
      years: '10+ Years',
      yearsLabel: 'of Research in Nature',
      heroTitle: 'The Essence of Nature in Every Drop',
      heroSub: 'At Saya, we believe true beauty lies in the simplicity and purity drawn from the heart of the earth.',
      storyLabel: 'Our Story',
      storyTitle: 'A Journey Born from a Passion for Nature',
      story1: 'Saya was founded on a simple vision: to create skincare products that respect nature\'s balance and modern human needs. We started in a small, quiet laboratory, blending botanical oils and herbal infusions with love and dedication.',
      story2: 'Today, we are proud to serve those who value quality and purity, while maintaining our original commitment to using the finest organic ingredients that nourish both skin and soul.',
      tagline: 'Saya, where earth meets beauty.',
      valuesTitle: 'Our Mission & Values',
      values: [
        { icon: 'eco', title: 'Organic Purity', body: 'We use 100% natural ingredients, carefully selected from sustainable farms that support the environment and local communities.' },
        { icon: 'spa', title: 'Care for All', body: 'Our products are designed to suit all skin types, focusing on ingredients that are both gentle and highly effective.' },
        { icon: 'science', title: 'Scientific Foundation', body: 'We combine ancient herbal wisdom with the latest scientific advances in skincare.' },
      ],
      ingredientsLabel: 'Our Ingredients',
      ingredientsTitle: 'Cleanliness Beyond Words',
      ingredientsBody: 'Every ingredient in our formulations is chosen for its therapeutic potency and safety. We refuse to use harsh chemicals, parabens, or synthetic fragrances.',
      ingredients: ['Cold-pressed plant oils', 'Organic wild herbal infusions', 'Unrefined natural butters'],
      shopCta: 'Shop Now',
      founderQuote: '"Beauty shouldn\'t be complicated. At Saya, we let nature care for your skin so you can express yourself with full confidence."',
      founderName: 'Sara Al-Fayez',
      founderRole: 'Founder & Creative Director',
    },
    reviews: { title: 'What They Say About Saya', sub: 'Real experiences from women who found the secret to radiance' },
    newsletter: {
      title: 'Join the Saya Family',
      body: 'Subscribe to our newsletter for exclusive beauty tips and 15% off your first order.',
      placeholder: 'Your email address',
      cta: 'Subscribe Now',
    },
    shop: {
      title: 'Our Natural Store',
      sub: 'Discover the secret of organic beauty extracted from the heart of nature, for the premium care you deserve.',
      filters: 'Categories',
      priceRange: 'Price Range',
      sortBy: 'Sort By',
      sortOptions: ['Newest', 'Price: Low to High', 'Price: High to Low', 'Best Selling'],
      addToCart: 'Add to Cart',
      categories: ['All', 'Skincare', 'Perfumes', 'Haircare', 'Offers'],
    },
    product: {
      rating: 'reviews',
      qty: 'Quantity:',
      addCart: 'Add to Cart',
      buyNow: 'Buy Now',
      tabs: ['Description', 'How to Use', 'Ingredients', 'Shipping & Returns'],
      related: 'You May Also Like',
      natural: 'Natural Ingredients',
      tested: 'Medically Tested',
    },
    checkout: {
      title: 'Checkout',
      sub: 'Please fill in the details below to confirm your order',
      shipping: 'Shipping Information',
      fullName: 'Full Name',
      phone: 'Phone Number',
      email: 'Email (optional)',
      city: 'City',
      address: 'Detailed Address',
      payment: 'Payment Method',
      cod: 'Cash on Delivery',
      codSub: 'Pay in cash to the delivery agent upon receipt',
      wallet: 'Wallet / Bank Transfer',
      walletSub: 'Vodafone Cash, InstaPay, or bank transfer',
      receipt: 'If you choose transfer, please attach a receipt photo:',
      upload: 'Upload Receipt',
      summary: 'Order Summary',
      discount: 'Discount Code',
      apply: 'Apply',
      subtotal: 'Subtotal',
      shippingCost: 'Shipping',
      total: 'Total',
      confirm: 'Confirm Order',
      terms: 'By clicking Confirm Order, you agree to our Terms & Conditions',
    },
    contact: {
      title: 'We\'d Love to Hear From You',
      sub: 'At Saya, we believe every skin is unique. Our specialist team is always here to answer your questions and help you choose the optimal routine for your natural beauty.',
      formTitle: 'Send Us a Message',
      fullName: 'Full Name',
      email: 'Email Address',
      subject: 'Subject',
      subjectOptions: ['General Inquiry', 'Skincare Consultation', 'Order Issue', 'Suggestions'],
      message: 'Your Message',
      send: 'Send Message',
      whatsapp: 'WhatsApp',
      emailLabel: 'Email',
      social: 'Follow Us on Social Media',
      location: 'Our Headquarters',
      address: 'Al-Rawdah District, King Abdullah Road, Riyadh, Saudi Arabia',
      directions: 'Get Directions',
      newsletterTitle: 'Join Saya\'s World',
      newsletterSub: 'Subscribe to our newsletter to receive the latest news about our natural products and exclusive offers.',
      newsletterCta: 'Subscribe Now',
    },
    tracking: {
      title: 'Track Your Order',
      sub: 'Enter your order number to follow the journey of your Saya products right to your door.',
      label: 'Order Number',
      placeholder: 'e.g. SY-12345',
      cta: 'Track Order',
      exampleTitle: 'Shipping Details (Example)',
      steps: ['Order Received', 'Preparing', 'Out for Delivery', 'Delivered'],
      stepIcons: ['receipt_long', 'inventory_2', 'local_shipping', 'home_pin'],
      helpText: 'Having trouble tracking your order?',
      helpCta: 'Talk to our Customer Care Team',
    },
    footer: {
      tagline: 'Your beauty from nature, with a modern touch. We believe in purity and effectiveness in every drop.',
      shop: 'Shop by Type',
      company: 'About Saya',
      contactTitle: 'Contact Us',
      copyright: '© 2024 Saya. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms & Conditions',
      address: 'Cairo, Egypt',
      phone: '+201102903151',
      emailAddr: 'hello@saya-skincare.com',
      links: {
        skincare: 'Skincare',
        perfumes: 'Perfumes',
        hair: 'Hair',
        about: 'About Saya',
        shipping: 'Shipping',
        tracking: 'Tracking',
        contact: 'Contact',
      },
    },
  },
}

export { t }

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ar')

  useEffect(() => {
    document.documentElement.lang = lang
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
  }, [lang])

  const toggle = () => setLang(l => l === 'ar' ? 'en' : 'ar')
  const tr = t[lang]

  return (
    <LanguageContext.Provider value={{ lang, toggle, tr }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
